### ISSUE TITLE
support relative URLs as Auto Add URL 

### ISSUE THREAD

**Issue by anteo** [m-ramizraja/redmine_group_owners#4]
I've got Exception suddenly when tried to use relative URL (e.g. /wiki/Page) as Auto Add URL:

![image](https://cloud.githubusercontent.com/assets/2268089/7533175/1a3e0e5e-f591-11e4-9b63-104fd82a56b4.png)

I think there is no need to check host part of URL at all, it's obvious that host should match on which Redmine is running.

**Comment by m-ramizraja** [comment]
I have removed host check.
Please try now.

**Comment by anteo** [comment]
it's ok now
