### ISSUE TITLE
How do i use auto-add URL feature

### ISSUE THREAD

**Issue by danaivehr** [m-ramizraja/redmine_group_owners#5]
Hi!

Great plugin, just what i searched for!

Would you please explain, how can i use aout-add URL feature, because i can't get it.
Just an example.

Tried to set full URL and relative and just a word, and then to go to that url, but nothing worked.

**Comment by m-ramizraja** [comment]
You can register a URL of your application and when any registered user visits that URL, he/she will be added to this group automatically.

I hope, it's not too late :P

**Comment by danaivehr** [comment]
Thank you for reply! I just can't get it though.

What are requirements for that URL? Should it be inside Redmine? Should i manually make that URL availible in apache?

Let's say my Remine is somewhere.com/redmine, and i want to auto add user by URL "somewhere.com/redmine/please_make_me_a_project_manager" to group "managers"

What should i do then? Seems to set auto-add URL in group "somewhere.com/redmine/please_make_me_a_project_manager" is not enough, cause it doesn't work (error 404).

Should i setup something on server side?

**Comment by m-ramizraja** [comment]
Yes, it should redmine inside URL. This could be any URL, say you want to add any user who visits **My page**, somewhere.com/my/page, to "My page visitors" group, you can simply add url "somewhere.com/my/page" to auto add url of the "My page visitors" group.

So, it could be any URL. Even you can enhance this plugin and add a route for your mentioned url, somewhere.com/redmine/please_make_me_a_project_manager. Then you can use this url as auto add url.

**Comment by danaivehr** [comment]
Thank you, got it. Works like you described.
